---
- name: leapp_missing_pkg | Install required leapp data package on public clouds
  vars:
    entry_title_pattern: Package "[-\w]+" is missing
    leapp_report_location: /var/log/leapp/leapp-report.json
  block:
    - name: leapp_missing_pkg | Check that the leapp-report.json exists
      ansible.builtin.stat:
        path: "{{ leapp_report_location }}"
      register: leapp_report_stat

    - name: leapp_missing_pkg | End play if no leapp report exists
      ansible.builtin.set_fact:
        leapp_report_missing: true
      when: leapp_report_stat.stat.exists is false
      failed_when: leapp_report_stat.stat.exists is false

    - name: leapp_missing_pkg | Read leapp report
      ansible.builtin.slurp:
        src: "{{ leapp_report_location }}"
      register: leappreport

    - name: leapp_missing_pkg | Parse leapp report to json
      ansible.builtin.set_fact:
        leappreportdata: "{{ leappreport.content | b64decode | from_json }}"

    - name: leapp_missing_pkg | Find matching entries
      ansible.builtin.set_fact:
        remediation: "{{ item.detail.remediations | selectattr('type', 'eq', 'command') | first }}"
      loop: "{{ leappreportdata.entries }}"
      when: item.title is match(entry_title_pattern) and (item.detail.remediations | selectattr('type', 'eq', 'command') | list | length > 0)

    - name: leapp_missing_pkg | End execution of playbook if no entry found in leapp report
      ansible.builtin.set_fact:
        leapp_report_missing: true
      failed_when: remediation is not defined

    - name: leapp_missing_pkg | Install the missing package via remediation command
      ansible.builtin.command: "{{ remediation.context | join(' ') }}"
      when: remediation is defined
      register: remediation_result
      changed_when: remediation_result.rc == 0

  rescue:
    - name: leapp_missing_pkg | Continue when leapp report is missing
      ansible.builtin.debug:
        msg: "Leapp report missing or did not contain any matches. Skipping this task."
      when: leapp_report_missing is defined and leapp_report_missing is true

...
