---
# tasks file for common
- name: Log directory exists
  ansible.builtin.file:
    path: "{{ log_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Check for existing log file
  ansible.builtin.stat:
    path: "{{ log_file }}"
  register: log_file_stat

- name: Fail if log file already exists
  ansible.builtin.fail:
    msg: Another RIPU playbook job is already running. See {{ log_file }} for details. If the previous job was aborted, rename the log file to clear this failure and try again.
  when: log_file_stat.stat.exists

- name: Create new log file
  ansible.builtin.copy:
    content: |
      {{ job_name }}
      Job started at {{ now(fmt='%Y-%m-%dT%H:%M:%SZ', utc=true) }}
    dest: "{{ log_file }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Archive log file

- name: /etc/ansible/facts.d directory exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Capture current ansible_facts for validation after upgrade
  ansible.builtin.copy:
    content: "{{ ansible_facts | ansible.builtin.combine({'ansible_local': {}}) }}"
    dest: /etc/ansible/facts.d/pre_ripu.fact
    mode: "0644"
    owner: root
    group: root

- name: Capture a list of non-rhel versioned packages
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail;
      export PATH={{ os_path }};
      rpm -qa | grep -ve '[\.|+]el{{ ansible_distribution_major_version }}' |
      grep -vE '^(gpg-pubkey|libmodulemd|katello-ca-consumer)' |
      sort
  register: unsigned_packages_pre
  changed_when: false
  failed_when:
    - unsigned_packages_pre.rc != 0
    - unsigned_packages_pre.stderr != ""

- name: Create fact with the non-rhel versioned packages list
  ansible.builtin.set_fact:
    non_rhel_packages: "{{ unsigned_packages_pre.stdout_lines }}"

- name: Capture the list of non-rhel versioned packages in a separate fact file
  ansible.builtin.copy:
    content: "{{ non_rhel_packages }}"
    dest: /etc/ansible/facts.d/non_rhel_packages.fact
    mode: "0644"
    owner: root
    group: root

...
