- name: backup vm 
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_files:
    - vars.yml
  
  tasks:
    - name: Create a snapshot for each VM
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        folder: "/Datacenter-Guz/vm/Ansible"
        name: "{{ item }}"
        state: present
        snapshot_name: dns_test
        description: prueba_dns_raul
      loop: "{{ vm_names }}"
      delegate_to: localhost
