---
# defaults file for remedations

reboot_timeout: 7200
post_reboot_delay: 120
leapp_report_location: /var/log/leapp/leapp-report.json
remediation_playbooks:
  - leapp_cifs_detected
  - leapp_corrupted_grubenv_file
  - leapp_custom_network_scripts_detected
  - leapp_deprecated_sshd_directive
  - leapp_firewalld_allowzonedrifting
  - leapp_firewalld_unsupported_tftp_client
  - leapp_loaded_removed_kernel_drivers
  - leapp_missing_efibootmgr
  - leapp_missing_pkg
  - leapp_missing_yum_plugins
  - leapp_multiple_kernels
  - leapp_newest_kernel_not_in_use
  - leapp_nfs_detected
  - leapp_non_persistent_partitions
  - leapp_non_standard_openssl_config
  - leapp_old_postgresql_data
  - leapp_pam_tally2
  - leapp_partitions_with_noexec
  - leapp_relative_symlinks
  - leapp_remote_using_root
  - leapp_rpms_with_rsa_sha1_detected
  - leapp_unavailable_kde
  - leapp_vdo_check_needed
remediation_todo: []
...
