version: '3.8'

networks:
  myvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.10.0/25
          gateway: 192.168.10.1

services:
  rocky7:
    image: apasoft/rocky9-ansible
    container_name: rocky7
    networks:
      myvlan:
        ipv4_address: 192.168.10.59
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
