---
- name: Extend disk space using LVM
  hosts: rhel9
  become: yes
  tasks:
    - name: Check if /dev/sda4 partition exists
      ansible.builtin.command: fdisk -l /dev/sda
      register: fdisk_output
      changed_when: false
      failed_when: false

    - name: Create new partition /dev/sda4 if it does not exist
      ansible.builtin.command: >
        echo -e "n\np\n4\n\n\nt\n4\n8e\nw\n" | fdisk /dev/sda
      when: "'sda4' not in fdisk_output.stdout"
      register: fdisk_result
      changed_when: fdisk_result.rc == 0

    - name: Initialize /dev/sda4 as a physical volume
      ansible.builtin.command: pvcreate /dev/sda4
      register: pvcreate_result
      changed_when: pvcreate_result.rc == 0
      failed_when: pvcreate_result.rc != 0 and 'already a physical volume' not in pvcreate_result.stderr

    - name: Extend volume group rhel with /dev/sda4
      ansible.builtin.command: vgextend rhel /dev/sda4
      register: vgextend_result
      changed_when: vgextend_result.rc == 0
      failed_when: vgextend_result.rc != 0 and 'already part of volume group' not in vgextend_result.stderr

    - name: Resize physical volume /dev/sda3
      ansible.builtin.command: pvresize /dev/sda3
      register: pvresize_result
      changed_when: pvresize_result.rc == 0

    - name: Extend logical volume /dev/rhel/root
      ansible.builtin.command: lvextend -l +100%FREE /dev/rhel/root
      register: lvextend_result
      changed_when: lvextend_result.rc == 0

    - name: Check filesystem type of /
      ansible.builtin.command: df -T /
      register: fs_type
      changed_when: false

    - name: Grow XFS filesystem
      ansible.builtin.command: xfs_growfs /
      when: "'xfs' in fs_type.stdout"
      register: xfs_growfs_result
      changed_when: xfs_growfs_result.rc == 0

    - name: Resize ext4 filesystem
      ansible.builtin.command: resize2fs /dev/mapper/rhel-root
      when: "'ext4' in fs_type.stdout"
      register: resize2fs_result
      changed_when: resize2fs_result.rc == 0
...
