---
- name: update-and-reboot | Ensure all updates are applied
  ansible.builtin.package:
    name: "*"
    state: latest # noqa package-latest
  register: updates_available
  async: "{{ async_timeout_maximum | int }}"
  poll: "{{ async_poll_interval | int }}"

- name: update-and-reboot | Reboot when updates applied
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_timeout }}"
    post_reboot_delay: "{{ post_reboot_delay }}"
  timeout: "{{ reboot_timeout }}"
  when: updates_available.changed # noqa: no-handler

...
