- name: Probar conexión a OpenShift
  hosts: localhost
  connection: local
  tasks:
    - name: Obtener información del cluster
      kubernetes.core.k8s_cluster_info:
      register: api_info

    - name: Mostrar versión del cluster
      debug:
        msg: "Conectado a OpenShift. Versión: {{ api_info.version.server_version.gitVersion }}"
