---
- name: Consultar Namespaces de OpenShift
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Obtener lista de todos los Namespaces
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        verify_ssl: false
      register: ns_list

    - name: Mostrar nombres de los Namespaces encontrados
      ansible.builtin.debug:
        msg: "Namespace encontrado: {{ item.metadata.name }}"
      loop: "{{ ns_list.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"

    - name: Resumen del clúster
      ansible.builtin.debug:
        msg: "El clúster tiene actualmente {{ ns_list.resources | length }} namespaces."
